//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premium
    {
        public int PremiumId { get; set; }
        public int ProductSellId { get; set; }
        public int EmployeeId { get; set; }
        public double Sum { get; set; }
        public Nullable<double> Premium1 { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    }
}
