//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int idProduction { get; set; }
        public int product { get; set; }
        public int amount { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int employee { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Products Products { get; set; }
    }
}
